name: snowglobe_collection
description: A SnowGlobe Collection App

# Aggiungi questa parte per specificare il constraint dell'SDK
environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter 
  supabase_flutter: ^2.8.4
  provider: ^6.1.2
  flutter_map: ^8.1.1
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  image_cropper: ^9.0.0
  image: ^4.5.3
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
